### PR TITLE
fix unit tests and replicate changes in olevba3

### PR DESCRIPTION
**Pull request by samiraguiar**

### CODE REVIEW

**Review by christian-intra2net — CHANGES_REQUESTED** [review]
The print() calls in is_rtf were just for testing/debugging. I should not have committed them at all. I think they do not "deserve" debug-log calls. Could you remove them completely?

**Comment by samiraguiar** [comment]
Done, Christian.

**Review by christian-intra2net — APPROVED** [review]
Perfect, thanks

**Comment by christian-intra2net** [comment]
I merged it into my branch, fixed a little error I created myself and created a pull request for decalage. Hope he likes it

**Pull request merged**
